;; SPDX-License-Identifier: MIT

(ns hive-datascript.swarm.coordination.config
  "Typed config for hive-mcp.swarm.datascript.coordination.* via hive-di defconfig.

   Replaces:
     - `(def ^:private stale-threshold-ms (* 2 60 1000))` (private constant)
       in hive-mcp.swarm.datascript.coordination, with an env-overridable
       :coordinator-stale-ms field.
     - Inline `(* 5 60 1000)` default in `cleanup-stale-claims!`, with an
       env-overridable :claim-stale-ms field.

   Resolution order (per field): default <- env <- caller overrides.

   Tests can override the resolver via with-redefs:

     (with-redefs [hive-mcp.swarm.datascript.coordination.config/coordination-config
                   (fn [] {:coordinator-stale-ms 1000 :claim-stale-ms 5000})]
       ...)

   Generated by defconfig:
     CoordinationConfig         — ADT
     CoordinationConfig-fields  — field registry
     CoordinationConfig-schema  — Malli schema
     resolve-CoordinationConfig — resolver fn (returns Result)

   Moved from hive-mcp.swarm.datascript.coordination.config (hive-mcp)."
  (:require [hive-di.core :refer [defconfig env]]
            [hive-dsl.result :as r]))

;; =============================================================================
;; CoordinationConfig — stale thresholds for coordinators and claims
;; =============================================================================

(defconfig CoordinationConfig
  :coordinator-stale-ms (env "HIVE_COORDINATION_COORDINATOR_STALE_MS"
                             :default (* 2 60 1000)
                             :type :int
                             :doc "Coordinator is considered stale after this many ms without heartbeat (default: 2 min).")
  :claim-stale-ms       (env "HIVE_COORDINATION_CLAIM_STALE_MS"
                             :default (* 5 60 1000)
                             :type :int
                             :doc "Claims older than this with no heartbeat are reaped (default: 5 min)."))

;; =============================================================================
;; Resolver helper — pure surface used by coordination.cleanup
;; =============================================================================

(defn- resolve-or-throw
  "Resolve a defconfig record into a plain map. Throws on resolution failure
   (defaults guarantee resolution under normal conditions)."
  [resolver overrides]
  (let [result (resolver overrides)]
    (if (r/ok? result)
      (:ok result)
      (throw (ex-info "coordination/config resolution failed"
                      {:result result :overrides overrides})))))

(defn coordination-config
  "Resolved CoordinationConfig as a plain map.

   Tests can rebind via `with-redefs`:
     (with-redefs [coordination-config
                   (constantly {:coordinator-stale-ms 1000 :claim-stale-ms 5000})]
       ...)"
  ([] (coordination-config {}))
  ([overrides]
   (resolve-or-throw resolve-CoordinationConfig overrides)))
